export const WebCamAction = {
  START : 'WEB_CAM_START',
  OFF: 'WEB_CAM_OFF',
  RECV: 'WEB_CAM_RECV'
};
export const ScreenCamAction = {
  START: "SCREEN_START",
  OFF: "SCREEN_OFF",
  RECV: "SCREEN_RECV"
};

export const UserAction = {
  ADD: "USER_ADD",
  REMOVE: "USER_REMOVE"
};
export const TokenAction = {
  GET: "GET_TOKEN",
  SUCCESS: "GET_TOKEN_SUCCESS"
};

export const WhiteBoardAction = {
  PDF_START: "PDF_START",
  SET_IMAGES: "SET_IMAGES",
  RESET_NUMPAGES: "RESET_PAGE",
  SET_PAGE: "SET_PAGE",
  SET_SHAPES: "SET_SHAPES",
  START_PRESENTATION_SUCCESS: "START_PRESENTATION_SUCCESS",
  START_PRESENTATION_REJECT: "START_PRESENTATION_REJECT",
  STOP_PRESENTATION: "STOP_PRESENTATION"
};

export const ADD_MESSAGE = "ADD_MESSAGE";
