/*
*/
/*
 MIT
*/
var Url=require("url"),spawn=require("child_process").spawn,fs=require("fs"),XMLHttpRequest=function(){var b=this,o=require("http"),p=require("https"),j,c,e={},n={"User-Agent":"node.js",Accept:"*/*"},h=!1,l=!1,m=n;this.UNSENT=0;this.OPENED=1;this.HEADERS_RECEIVED=2;this.LOADING=3;this.DONE=4;this.readyState=this.UNSENT;this.onreadystatechange=null;this.responseXML=this.responseText="";this.statusText=this.status=null;this.open=function(a,b,f,c,g){e={method:a,url:b.toString(),async:"boolean"!==typeof f?
!0:f,user:c||null,password:g||null};this.abort();i(this.OPENED)};this.setRequestHeader=function(a,b){if(this.readyState!=this.OPENED)throw"INVALID_STATE_ERR: setRequestHeader can only be called when state is OPEN";if(h)throw"INVALID_STATE_ERR: send flag is true";m[a]=b};this.getResponseHeader=function(a){return this.readyState>this.OPENED&&c.headers[a]&&!l?c.headers[a]:null};this.getAllResponseHeaders=function(){if(this.readyState<this.HEADERS_RECEIVED||l)return"";var a="",b;for(b in c.headers)a+=
b+": "+c.headers[b]+"\r\n";return a.substr(0,a.length-2)};this.send=function(a){if(this.readyState!=this.OPENED)throw"INVALID_STATE_ERR: connection must be opened before send() is called";if(h)throw"INVALID_STATE_ERR: send has already been called";var k=!1,f=Url.parse(e.url);switch(f.protocol){case "https:":k=!0;case "http:":var d=f.hostname;break;case void 0:case "":d="localhost";break;default:throw"Protocol not supported.";}var g=f.port||(k?443:80),f=f.pathname+(f.search?f.search:"");this.setRequestHeader("Host",
d);if(e.user){"undefined"==typeof e.password&&(e.password="");var n=new Buffer(e.user+":"+e.password);m.Authorization="Basic "+n.toString("base64")}"GET"==e.method||"HEAD"==e.method?a=null:a&&(this.setRequestHeader("Content-Length",Buffer.byteLength(a)),m["Content-Type"]||this.setRequestHeader("Content-Type","text/plain;charset=UTF-8"));d={host:d,port:g,path:f,method:e.method,headers:m};l=!1;if(!e.hasOwnProperty("async")||e.async){k=k?p.request:o.request;h=!0;if("function"===typeof b.onreadystatechange)b.onreadystatechange();
j=k(d,function(a){c=a;c.setEncoding("utf8");i(b.HEADERS_RECEIVED);b.status=c.statusCode;c.on("data",function(a){if(a)b.responseText=b.responseText+a;h&&i(b.LOADING)});c.on("end",function(){if(h){i(b.DONE);h=false}});c.on("error",function(a){b.handleError(a)})}).on("error",function(a){b.handleError(a)});a&&j.write(a);j.end()}else{g=".node-xmlhttprequest-sync-"+process.pid;fs.writeFileSync(g,"","utf8");a="var http = require('http'), https = require('https'), fs = require('fs');var doRequest = http"+
(k?"s":"")+".request;var options = "+JSON.stringify(d)+";var responseText = '';var req = doRequest(options, function(response) {response.setEncoding('utf8');response.on('data', function(chunk) {responseText += chunk;});response.on('end', function() {fs.writeFileSync('"+g+"', 'NODE-XMLHTTPREQUEST-STATUS:' + response.statusCode + ',' + responseText, 'utf8');});response.on('error', function(error) {fs.writeFileSync('"+g+"', 'NODE-XMLHTTPREQUEST-ERROR:' + JSON.stringify(error), 'utf8');});}).on('error', function(error) {fs.writeFileSync('"+
g+"', 'NODE-XMLHTTPREQUEST-ERROR:' + JSON.stringify(error), 'utf8');});"+(a?"req.write('"+a.replace(/'/g,"\\'")+"');":"")+"req.end();";for(syncProc=spawn(process.argv[0],["-e",a]);""==(b.responseText=fs.readFileSync(g,"utf8")););syncProc.stdin.end();fs.unlinkSync(g);b.responseText.match(/^NODE-XMLHTTPREQUEST-ERROR:/)?(a=b.responseText.replace(/^NODE-XMLHTTPREQUEST-ERROR:/,""),b.handleError(a)):(b.status=b.responseText.replace(/^NODE-XMLHTTPREQUEST-STATUS:([0-9]*),.*/,"$1"),b.responseText=b.responseText.replace(/^NODE-XMLHTTPREQUEST-STATUS:[0-9]*,(.*)/,
"$1"),i(b.DONE))}};this.handleError=function(a){this.status=503;this.statusText=a;this.responseText=a.stack;l=!0;i(this.DONE)};this.abort=function(){j&&(j.abort(),j=null);m=n;this.responseXML=this.responseText="";l=!0;if(this.readyState!==this.UNSENT&&(this.readyState!==this.OPENED||h)&&this.readyState!==this.DONE)h=!1,i(this.DONE);this.readyState=this.UNSENT};var d={};this.addEventListener=function(a,b){a in d||(d[a]=[]);d[a].push(b)};var i=function(a){b.readyState=a;if("function"===typeof b.onreadystatechange)b.onreadystatechange();
if("readystatechange"in d)for(var a=d.readystatechange.length,c=0;c<a;c++)d.readystatechange[c].call(b)}};
var CryptoJS=CryptoJS||function(d,c){var m={},a=m.lib={},b=a.Base=function(){function j(){}return{extend:function(a){j.prototype=this;var e=new j;a&&e.mixIn(a);e.$super=this;return e},create:function(){var j=this.extend();j.init.apply(j,arguments);return j},init:function(){},mixIn:function(j){for(var a in j)j.hasOwnProperty(a)&&(this[a]=j[a]);j.hasOwnProperty("toString")&&(this.toString=j.toString)},clone:function(){return this.$super.extend(this)}}}(),g=a.WordArray=b.extend({init:function(j,a){j=
this.words=j||[];this.sigBytes=a!=c?a:4*j.length},toString:function(j){return(j||f).stringify(this)},concat:function(j){var a=this.words,e=j.words,b=this.sigBytes,j=j.sigBytes;this.clamp();if(b%4)for(var g=0;g<j;g++)a[b+g>>>2]|=(e[g>>>2]>>>24-8*(g%4)&255)<<24-8*((b+g)%4);else if(65535<e.length)for(g=0;g<j;g+=4)a[b+g>>>2]=e[g>>>2];else a.push.apply(a,e);this.sigBytes+=j;return this},clamp:function(){var j=this.words,a=this.sigBytes;j[a>>>2]&=4294967295<<32-8*(a%4);j.length=d.ceil(a/4)},clone:function(){var j=
b.clone.call(this);j.words=this.words.slice(0);return j},random:function(j){for(var a=[],e=0;e<j;e+=4)a.push(4294967296*d.random()|0);return g.create(a,j)}}),l=m.enc={},f=l.Hex={stringify:function(a){for(var e=a.words,a=a.sigBytes,g=[],b=0;b<a;b++){var h=e[b>>>2]>>>24-8*(b%4)&255;g.push((h>>>4).toString(16));g.push((h&15).toString(16))}return g.join("")},parse:function(a){for(var e=a.length,b=[],h=0;h<e;h+=2)b[h>>>3]|=parseInt(a.substr(h,2),16)<<24-4*(h%8);return g.create(b,e/2)}},k=l.Latin1={stringify:function(a){for(var e=
a.words,a=a.sigBytes,b=[],g=0;g<a;g++)b.push(String.fromCharCode(e[g>>>2]>>>24-8*(g%4)&255));return b.join("")},parse:function(a){for(var e=a.length,b=[],h=0;h<e;h++)b[h>>>2]|=(a.charCodeAt(h)&255)<<24-8*(h%4);return g.create(b,e)}},e=l.Utf8={stringify:function(a){try{return decodeURIComponent(escape(k.stringify(a)))}catch(e){throw Error("Malformed UTF-8 data");}},parse:function(a){return k.parse(unescape(encodeURIComponent(a)))}},h=a.BufferedBlockAlgorithm=b.extend({reset:function(){this._data=g.create();
this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=e.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var e=this._data,b=e.words,h=e.sigBytes,f=this.blockSize,l=h/(4*f),l=a?d.ceil(l):d.max((l|0)-this._minBufferSize,0),a=l*f,h=d.min(4*a,h);if(a){for(var k=0;k<a;k+=f)this._doProcessBlock(b,k);k=b.splice(0,a);e.sigBytes-=h}return g.create(k,h)},clone:function(){var a=b.clone.call(this);a._data=this._data.clone();return a},_minBufferSize:0});a.Hasher=h.extend({init:function(){this.reset()},
reset:function(){h.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);this._doFinalize();return this._hash},clone:function(){var a=h.clone.call(this);a._hash=this._hash.clone();return a},blockSize:16,_createHelper:function(a){return function(e,b){return a.create(b).finalize(e)}},_createHmacHelper:function(a){return function(e,b){return p.HMAC.create(a,b).finalize(e)}}});var p=m.algo={};return m}(Math);
(function(){var d=CryptoJS,c=d.lib,m=c.WordArray,c=c.Hasher,a=[],b=d.algo.SHA1=c.extend({_doReset:function(){this._hash=m.create([1732584193,4023233417,2562383102,271733878,3285377520])},_doProcessBlock:function(b,l){for(var f=this._hash.words,k=f[0],e=f[1],h=f[2],d=f[3],j=f[4],c=0;80>c;c++){if(16>c)a[c]=b[l+c]|0;else{var m=a[c-3]^a[c-8]^a[c-14]^a[c-16];a[c]=m<<1|m>>>31}m=(k<<5|k>>>27)+j+a[c];m=20>c?m+((e&h|~e&d)+1518500249):40>c?m+((e^h^d)+1859775393):60>c?m+((e&h|e&d|h&d)-1894007588):m+((e^h^d)-
899497514);j=d;d=h;h=e<<30|e>>>2;e=k;k=m}f[0]=f[0]+k|0;f[1]=f[1]+e|0;f[2]=f[2]+h|0;f[3]=f[3]+d|0;f[4]=f[4]+j|0},_doFinalize:function(){var a=this._data,b=a.words,f=8*this._nDataBytes,c=8*a.sigBytes;b[c>>>5]|=128<<24-c%32;b[(c+64>>>9<<4)+15]=f;a.sigBytes=4*b.length;this._process()}});d.SHA1=c._createHelper(b);d.HmacSHA1=c._createHmacHelper(b)})();
(function(){var d=CryptoJS,c=d.enc.Utf8;d.algo.HMAC=d.lib.Base.extend({init:function(d,a){d=this._hasher=d.create();"string"==typeof a&&(a=c.parse(a));var b=d.blockSize,g=4*b;a.sigBytes>g&&(a=d.finalize(a));for(var l=this._oKey=a.clone(),f=this._iKey=a.clone(),k=l.words,e=f.words,h=0;h<b;h++)k[h]^=1549556828,e[h]^=909522486;l.sigBytes=f.sigBytes=g;this.reset()},reset:function(){var c=this._hasher;c.reset();c.update(this._iKey)},update:function(c){this._hasher.update(c);return this},finalize:function(c){var a=
this._hasher,c=a.finalize(c);a.reset();return a.finalize(this._oKey.clone().concat(c))}})})();var N=N||{};N.authors=["aalonsog@dit.upm.es","prodriguez@dit.upm.es","jcervino@dit.upm.es"];N.version=0.1;N=N||{};
N.Base64=function(){var d,c,m,a,b,g,l,f,k;d="A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9,+,/".split(",");c=[];for(b=0;b<d.length;b+=1)c[d[b]]=b;g=function(e){m=e;a=0};l=function(){var e;if(!m||a>=m.length)return-1;e=m.charCodeAt(a)&255;a+=1;return e};f=function(){if(!m)return-1;for(;;){if(a>=m.length)return-1;var e=m.charAt(a);a+=1;if(c[e])return c[e];if("A"===e)return 0}};k=function(a){a=a.toString(16);1===a.length&&(a=
"0"+a);return unescape("%"+a)};return{encodeBase64:function(a){var b,c,f;g(a);a="";b=Array(3);c=0;for(f=!1;!f&&-1!==(b[0]=l());)if(b[1]=l(),b[2]=l(),a+=d[b[0]>>2],-1!==b[1]?(a+=d[b[0]<<4&48|b[1]>>4],-1!==b[2]?(a+=d[b[1]<<2&60|b[2]>>6],a+=d[b[2]&63]):(a+=d[b[1]<<2&60],a+="=",f=!0)):(a+=d[b[0]<<4&48],a+="=",a+="=",f=!0),c+=4,76<=c)a+="\n",c=0;return a},decodeBase64:function(a){var b,c;g(a);a="";b=Array(4);for(c=!1;!c&&-1!==(b[0]=f())&&-1!==(b[1]=f());)b[2]=f(),b[3]=f(),a+=k(b[0]<<2&255|b[1]>>4),-1!==
b[2]?(a+=k(b[1]<<4&255|b[2]>>2),-1!==b[3]?a+=k(b[2]<<6&255|b[3]):c=!0):c=!0;return a}}}(N);N=N||{};
N.API=function(d){var c,m;updateRoom=function(a,b,g,l,f,d){c(g,l,"PUT",{name:b,options:f},"rooms/"+a,d)};c=function(a,b,c,l,f,k,e,h){var p,j,r,q,o,n;void 0===k?(p=d.API.params.service,j=d.API.params.key,f=d.API.params.url+f):(p=k.service,j=k.key,f=k.url+f);""===p||""===j?console.log("ServiceID and Key are required!!"):(k=(new Date).getTime(),r=Math.floor(99999*Math.random()),q=k+","+r,o="MAuth realm=http://marte3.dit.upm.es,mauth_signature_method=HMAC_SHA1",e&&h&&(e=formatString(e),o=o+",mauth_username="+e+
",mauth_role="+h,q+=","+e+","+h),e=m(q,j),o=o+",mauth_serviceid="+p+",mauth_cnonce="+r+",mauth_timestamp="+k+",mauth_signature="+e,n=new XMLHttpRequest,n.onreadystatechange=function(){if(n.readyState===4)switch(n.status){case 100:case 200:case 201:case 202:case 203:case 204:case 205:a(n.responseText);break;case 400:b!==void 0&&b("400 Bad Request");break;case 401:b!==void 0&&b("401 Unauthorized");break;case 403:b!==void 0&&b("403 Forbidden");break;default:b!==void 0&&b(n.status+" Error"+n.responseText)}},
n.open(c,f,!0),n.setRequestHeader("Authorization",o),void 0!==l)?(n.setRequestHeader("Content-Type","application/json"),n.send(JSON.stringify(l))):n.send()};m=function(a,b){var c;c=CryptoJS.HmacSHA1(a,b).toString(CryptoJS.enc.Hex);return d.Base64.encodeBase64(c)};formatString=function(a){a=a.toLowerCase();non_asciis={a:"[\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5]",ae:"\u00e6",c:"\u00e7",e:"[\u00e8\u00e9\u00ea\u00eb]",i:"[\u00ec\u00ed\u00ee\u00ef]",n:"\u00f1",o:"[\u00f2\u00f3\u00f4\u00f5\u00f6]",oe:"\u0153",
u:"[\u00f9\u00fa\u00fb\u0171\u00fc]",y:"[\u00fd\u00ff]"};for(i in non_asciis)a=a.replace(RegExp(non_asciis[i],"g"),i);return a};return{params:{service:void 0,key:void 0,url:void 0},init:function(a,b,c){d.API.params.service=a;d.API.params.key=b;d.API.params.url=c},createRoom:function(a,b,g,d,f){d||(d={});c(function(a){a=JSON.parse(a);b(a)},g,"POST",{name:a,options:d},"rooms",f)},getRooms:function(a,b,g){c(a,b,"GET",void 0,"rooms",g)},getRoom:function(a,b,g,d){c(b,g,"GET",void 0,"rooms/"+a,d)},updateRoom:updateRoom,
patchRoom:function(a,b,g,d,f,k){c(g,d,"PATCH",{name:b,options:f},"rooms/"+a,k)},deleteRoom:function(a,b,g,d){c(b,g,"DELETE",void 0,"rooms/"+a,d)},createToken:function(a,b,g,d,f,k){c(d,f,"POST",void 0,"rooms/"+a+"/tokens",k,b,g)},createService:function(a,b,g,d,f){c(g,d,"POST",{name:a,key:b},"services/",f)},getServices:function(a,b,g){c(a,b,"GET",void 0,"services/",g)},getService:function(a,b,g,d){c(b,g,"GET",void 0,"services/"+a,d)},deleteService:function(a,b,d,l){c(b,d,"DELETE",void 0,"services/"+
a,l)},getUsers:function(a,b,d,l){c(b,d,"GET",void 0,"rooms/"+a+"/users/",l)},getUser:function(a,b,d,l,f){c(d,l,"GET",void 0,"rooms/"+a+"/users/"+b,f)},deleteUser:function(a,b,d,l,f){c(d,l,"DELETE",void 0,"rooms/"+a+"/users/"+b,f)}}}(N);
module.exports = N;
